# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: <%= ENV['domain_name'] %>
  external_port: <%= ENV['external_port'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>
  api_endpoint: <%= ENV['api_endpoint'] %>
  google_analytic_tracker: <%= ENV['google_analytics_tracker'] %>
  geoportail_api_key: <%= ENV['geoportail_api_key'] %>
  newrelic_licence_key: <%= ENV['newrelic_licence_key'] %>
  osrm_endpoint: <%= ENV['osrm_endpoint'] %>
  smtp_delivery_method: <%= ENV['smtp_delivery_method'] %>
  smtp_host: <%= ENV['smtp_host'] %>
  smtp_port: <%= ENV['smtp_port'] %>
  smtp_domain: <%= ENV['smtp_domain'] %>
  smtp_user_name: <%= ENV['smtp_user_name'] %>
  smtp_password: <%= ENV['smtp_password'] %>
  smtp_authentication: <%= ENV['smtp_authentication'] %>
  smtp_openssl_verify_mode: <%= ENV['smtp_openssl_verify_mode'] %>
  smtp_enable_starttls_auto: <%= ENV['smtp_enable_starttls_auto'] %>
  mailer_sender: <%= ENV['mailer_sender'] %>
  app_version: <%= ENV['app_version'] %>
  devise_secret_key: <%= ENV['devise_secret_key'] %>
  capistrano_deploy_user: <%= ENV['capistrano_deploy_user'] %>

test:
  secret_key_base: '54f61aab23322611dd0bbf73b7f034db34281f7f4b3c4992eaaff20ecc9673bbd467beaa6fcb48379ca69b80bc5662deac4e33ca144f2482146123d3e966016a'
  api_endpoint: "http://localhost:8080/chouette_iev/"
  osrm_endpoint: "http://router.project-osrm.org"
  app_version: 'Testing'
  devise_secret_key: '54f61aab23322611dd0bbf73b7f034db34281f7f4b3c4992eaaff20ecc9673bbd467beaa6fcb48379ca69b80bc5662deac4e33ca144f2482146123d3e966016a'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV['domain_name'] %>
  external_port: <%= ENV['external_port'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>
  api_endpoint: <%= ENV['api_endpoint'] %>
  google_analytic_tracker: <%= ENV['google_analytics_tracker'] %>
  geoportail_api_key: <%= ENV['geoportail_api_key'] %>
  newrelic_licence_key: <%= ENV['newrelic_licence_key'] %>
  osrm_endpoint: <%= ENV['osrm_endpoint'] %>
  smtp_delivery_method: <%= ENV['smtp_delivery_method'] %>
  smtp_host: <%= ENV['smtp_host'] %>
  smtp_port: <%= ENV['smtp_port'] %>
  smtp_domain: <%= ENV['smtp_domain'] %>
  smtp_user_name: <%= ENV['smtp_user_name'] %>
  smtp_password: <%= ENV['smtp_password'] %>
  smtp_authentication: <%= ENV['smtp_authentication'] %>
  smtp_openssl_verify_mode: <%= ENV['smtp_openssl_verify_mode'] %>
  smtp_enable_starttls_auto: <%= ENV['smtp_enable_starttls_auto'] %>
  mailer_sender: <%= ENV['mailer_sender'] %>
  app_version: <%= ENV['app_version'] %>
  devise_secret_key: <%= ENV['devise_secret_key'] %>

