# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e901adb90fc1fff22f7237d138ef232a5425b67e81ccb3ce7003aab2c002d35a7c3d593c0fca3dcb21e8c911a8260c984a830d1d61776ad3005eb373abebc695
  api_endpoint: "http://chouette:8080/chouette_iev/"
  google_analytic_tracker: "UA-AAAAAAAA"
  # geoportail_api_key: "aaaaaaaaaaaaaaaaaaaaaa"

test:
  secret_key_base: 54f61aab23322611dd0bbf73b7f034db34281f7f4b3c4992eaaff20ecc9673bbd467beaa6fcb48379ca69b80bc5662deac4e33ca144f2482146123d3e966016a
  api_endpoint: "http://chouette:8080/chouette_iev/"
  google_analytic_tracker: "UA-AAAAAAAA"
  # geoportail_api_key: "aaaaaaaaaaaaaaaaaaaaaa"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 54f61aab23322611dd0bbf73b7f034db34281f7f4b3c4992eaaff20ecc9673bbd467beaa6fcb48379ca69b80bc5662deac4e33ca144f2482146123d3e966016a
  api_endpoint: "http://chouette:8080/chouette_iev/"
  google_analytic_tracker: "UA-AAAAAAAA"
  # geoportail_api_key: "aaaaaaaaaaaaaaaaaaaaaa"
