env: staging

sql:
  instance: entur-ror-test:europe-west1:chouette-db-pg13=tcp:5432

chouetteUrl: http://chouette.tst.entur.internal
osrmRailUrl: http://osrm-rail.tst.entur.internal
osrmBusUrl: http://osrm-bus.tst.entur.internal
osrmWaterUrl: http://osrm-water.tst.entur.internal